'use client'
import { ReactNode } from 'react'
import { clsx } from 'clsx'
import { twMerge } from 'tailwind-merge'
import { X, Inbox } from 'lucide-react'
export const cn = (...a: any[]) => twMerge(clsx(a))
export const Card = ({ className, children }: { className?: string; children: ReactNode }) => <div className={cn('rounded-xl border border-black/[0.08] bg-white', className)}>{children}</div>
const T: Record<string, string> = { green: 'bg-emerald-50 text-emerald-800 ring-emerald-600/20', amber: 'bg-amber-50 text-amber-800 ring-amber-600/20', red: 'bg-red-50 text-red-700 ring-red-600/20', gray: 'bg-slate-100 text-slate-700 ring-slate-500/15', navy: 'bg-navy text-white ring-transparent' }
export const Badge = ({ tone = 'gray', children }: { tone?: string; children: ReactNode }) => <span className={cn('inline-flex items-center rounded-md px-2 py-0.5 text-[11px] font-medium ring-1 ring-inset whitespace-nowrap', T[tone])}>{children}</span>
export const Btn = ({ v = 'primary', className, ...p }: any) => <button {...p} className={cn('inline-flex items-center justify-center gap-1.5 rounded-lg px-3 py-1.5 text-[13px] font-semibold transition disabled:opacity-40 disabled:pointer-events-none', v === 'primary' ? 'bg-brand text-white hover:bg-brand-dark' : v === 'ghost' ? 'text-slate-600 hover:bg-slate-100' : 'border border-slate-200 bg-white hover:bg-slate-50', className)} />
export const Kpi = ({ label, value, sub, tone }: { label: string; value: ReactNode; sub?: string; tone?: string }) => <Card className="p-4"><div className="text-xs font-medium text-slate-500">{label}</div><div className={cn('num mt-1 font-display text-[28px] font-semibold leading-tight tracking-tight', tone)}>{value}</div>{sub && <div className="mt-0.5 text-xs text-slate-500">{sub}</div>}</Card>
export const Head = ({ title, sub, right }: { title: string; sub?: string; right?: ReactNode }) => <div className="mb-6 flex items-end justify-between gap-4"><div><h1 className="font-display text-[30px] font-semibold leading-tight tracking-tight">{title}</h1>{sub && <p className="mt-0.5 text-sm text-slate-500">{sub}</p>}</div>{right}</div>
export const Th = ({ children }: { children?: ReactNode }) => <th className="whitespace-nowrap border-b px-3 py-2.5 text-left text-xs font-medium text-slate-500">{children}</th>
export const Td = ({ children, className }: { children?: ReactNode; className?: string }) => <td className={cn('num border-b border-slate-100 px-3 py-2.5 text-[13px]', className)}>{children}</td>
export const Table = ({ head, children, empty }: { head: string[]; children: ReactNode; empty?: boolean }) => <div className="overflow-x-auto"><table className="w-full border-collapse"><thead><tr>{head.map(h => <Th key={h}>{h}</Th>)}</tr></thead><tbody>{children}</tbody></table>{empty && <Empty text="No records match these filters" />}</div>
export const Empty = ({ text }: { text: string }) => <div className="flex flex-col items-center gap-2 py-12 text-sm text-slate-400"><Inbox size={22} />{text}</div>
export const Sel = ({ value, onChange, opts, all }: { value: string; onChange: (v: string) => void; opts: string[]; all?: string }) => <select value={value} onChange={e => onChange(e.target.value)} className="rounded-lg border border-slate-200 bg-white px-2.5 py-1.5 text-[13px] text-ink">{all && <option value="">{all}</option>}{opts.map(o => <option key={o}>{o}</option>)}</select>
export const Bar = ({ pct, tone = 'bg-brand' }: { pct: number; tone?: string }) => <div className="h-1.5 w-full rounded-full bg-slate-100"><div className={cn('h-full rounded-full', tone)} style={{ width: `${Math.min(100, pct)}%` }} /></div>
export const Modal = ({ title, onClose, children, wide }: { title: string; onClose: () => void; children: ReactNode; wide?: boolean }) => <div className="fixed inset-0 z-50 flex items-center justify-center bg-navy/50 p-4" onClick={onClose}><div onClick={e => e.stopPropagation()} className={cn('rise max-h-[90vh] w-full overflow-y-auto rounded-2xl bg-white shadow-2xl', wide ? 'max-w-3xl' : 'max-w-md')}><div className="sticky top-0 flex items-center justify-between border-b bg-white px-5 py-3"><h2 className="font-bold">{title}</h2><button onClick={onClose} className="rounded p-1 hover:bg-slate-100"><X size={16} /></button></div><div className="p-5">{children}</div></div></div>
